/-
  **Compositionality from a partner policy, over an arbitrary lattice.**

  `TwoPoint.lean` proves that a component composes once its partner has a causal
  policy, but under `Omniscient`: the users of the ℓ-invisible channels are assumed
  to see everything, which holds in the two-point lattice and fails in general --
  and in particular fails at a layer of the peeling of `Layered.lean`, where such a
  user sees only `↓γ(a)`.

  `Omniscient` is used in exactly one place: to know that the partner's policy,
  read off the component's trace, respects the views of the invisible channels.
  That is a property of the *policy*, not of the lattice, so we require it of the
  policy instead.  The result is the same theorem with no hypothesis on the
  lattice at all, and the old one is the special case where `Omniscient` makes
  every policy respectful.
-/
import InteractiveNI.TwoPoint
import InteractiveNI.Coalition

namespace InteractiveNI

open Classical
attribute [local instance] Classical.propDecidable

namespace Sec

variable {Level Channel Value : Type} {S : Sec Level Channel}

/-- A partner policy is **respectful** when it never lets a channel's user
    distinguish two traces that user cannot already tell apart. -/
def Respectful (S : Sec Level Channel)
    (φ : List (Lbl Channel Value) → List (Lbl Channel Value)) : Prop :=
  ∀ (a : Channel) (u₁ u₂ : List (Lbl Channel Value)),
    S.teq (S.valL a) u₁ u₂ → S.teq (S.valL a) (φ u₁) (φ u₂)

/-- Under `Omniscient` every policy with a constant ℓ-view is respectful, so the
    hypothesis below is weaker than the one of `TwoPoint.lean`. -/
theorem respectful_of_omniscient {ℓ : Level} (hom : Omniscient S Value ℓ)
    {φ : List (Lbl Channel Value) → List (Lbl Channel Value)}
    {b : List (Lbl Channel Value)} (hconst : ∀ u, S.teq ℓ (φ u) b) :
    S.Respectful φ := by
  intro a u₁ u₂ h
  by_cases hl : S.le (S.valL a) ℓ
  · exact teq_mono hl ((hconst u₁).trans (hconst u₂).symm)
  · rw [hom a hl u₁ u₂ h]

/-- The insertion generated by a respectful partner policy. -/
noncomputable def policyIns' (hpub : PublicPresence S) {ℓ : Level}
    (hpresℓ : ∀ a : Channel, S.le (S.presL a) ℓ)
    (p : List Bool) (φ : List (Lbl Channel Value) → List (Lbl Channel Value))
    (b : List (Lbl Channel Value)) (hconst : ∀ u, S.teq ℓ (φ u) b)
    (hresp : S.Respectful φ) : Insertion S Value where
  σ := fun _ u => weave p u (φ u)
  resp_val := fun a t₁ t₂ h => teq_weave hpub h (hresp a t₁ t₂ h)
  resp_pres := fun a t₁ t₂ h =>
    teq_weave hpub h (teq_mono (hpresℓ a) ((hconst t₁).trans (hconst t₂).symm))

@[simp] theorem policyIns'_σ (hpub : PublicPresence S) {ℓ : Level}
    (hpresℓ : ∀ a : Channel, S.le (S.presL a) ℓ)
    (p : List Bool) (φ : List (Lbl Channel Value) → List (Lbl Channel Value))
    (b : List (Lbl Channel Value)) (hconst : ∀ u, S.teq ℓ (φ u) b)
    (hresp : S.Respectful φ) (a : Channel) (u : List (Lbl Channel Value)) :
    (policyIns' hpub hpresℓ p φ b hconst hresp).σ a u = weave p u (φ u) := rfl

/-- **Lemma (★), composed form, with no hypothesis on the lattice.** -/
def HasPolicy' (hpub : PublicPresence S) {St₂ : Type}
    (step₂ : St₂ → Act Channel Value → St₂ → Prop) (sB : St₂) (ℓ : Level)
    (w : S.Strategy Value) (p : List Bool) (b : List (Lbl Channel Value)) : Prop :=
  ∃ φ : List (Lbl Channel Value) → List (Lbl Channel Value),
    (∀ u, S.teq ℓ (φ u) b) ∧ S.Respectful φ ∧
    (∀ u t₁, t₁ <+: u → weave p t₁ (φ t₁) = weave p t₁ (φ u)) ∧
    (∀ u, S.produces step₂ ((weaveIns hpub (p.map not) u).induced w) sB (φ u))

theorem hasPolicy'_of_hasPolicy (hpub : PublicPresence S) {St₂ : Type}
    {step₂ : St₂ → Act Channel Value → St₂ → Prop} {sB : St₂} {ℓ : Level}
    (hom : Omniscient S Value ℓ) {w : S.Strategy Value} {p : List Bool}
    {b : List (Lbl Channel Value)} (h : HasPolicy hpub step₂ sB ℓ w p b) :
    HasPolicy' hpub step₂ sB ℓ w p b := by
  obtain ⟨φ, hconst, hcaus, hrun⟩ := h
  exact ⟨φ, hconst, respectful_of_omniscient hom hconst, hcaus, hrun⟩

/-- **Compositionality from a partner policy, over an arbitrary lattice.**  With
    `B`'s policy in hand, `A` is re-planned by its own noninterference and the two
    fit together with no fixed point -- and now with no constraint on `⊑`. -/
theorem compositional_of_policy' (hpub : PublicPresence S)
    {St₁ St₂ : Type} {step₁ : St₁ → Act Channel Value → St₁ → Prop}
    {step₂ : St₂ → Act Channel Value → St₂ → Prop} {sA : St₁} {sB : St₂}
    {ℓ : Level} (hpresℓ : ∀ a : Channel, S.le (S.presL a) ℓ)
    (hA : S.INI step₁ (fun _ => True) sA)
    {w₁ w₂ : S.Strategy Value} (hw : S.seq ℓ w₁ w₂)
    {t : List (Lbl Channel Value)}
    (ht : S.produces (parStep step₁ step₂) w₁ (sA, sB) t)
    (hpol : ∀ p b, (∃ q, Reach step₂ sB b q) → HasPolicy' hpub step₂ sB ℓ w₂ p b) :
    ∃ t₂, S.produces (parStep step₁ step₂) w₂ (sA, sB) t₂ ∧ S.teq ℓ t t₂ := by
  obtain ⟨q, hreach⟩ := ht.1
  obtain ⟨a, b, hRa, hRb, hI⟩ := par_decompose hreach
  obtain ⟨p, hp, hE⟩ := hI.exists_weave
  have hcons : S.consistent w₁ (weave p a b) := hp ▸ ht.2
  obtain ⟨φ, hconst, hresp, hcaus, hrun⟩ := hpol p b ⟨q.2, hRb⟩
  have hAprod : S.produces step₁ ((weaveIns hpub p b).induced w₁) sA a :=
    ⟨⟨q.1, hRa⟩, consistent_weave_left hpub hE hcons⟩
  have hseq : S.seq ℓ ((weaveIns hpub p b).induced w₁)
      ((policyIns' hpub hpresℓ p φ b hconst hresp).induced w₂) := by
    intro α u
    refine ⟨fun hl => ?_, fun hl => ?_⟩ <;>
      simp only [Insertion.induced_apply, weaveIns_σ, policyIns'_σ]
    · have : w₂.ω α (weave p u b) = w₂.ω α (weave p u (φ u)) :=
        w₂.resp_val α _ _ (teq_mono hl (teq_weave hpub (rfl : S.teq ℓ u u) (hconst u).symm))
      rw [(hw α (weave p u b)).1 hl, this]
    · refine dotEq.trans ((hw α (weave p u b)).2 hl) ?_
      exact w₂.resp_pres α _ _ (teq_mono hl (teq_weave hpub (rfl : S.teq ℓ u u) (hconst u).symm))
  obtain ⟨a₂, ha₂, hta⟩ := hA ℓ _ _ trivial trivial hseq a hAprod
  have hBrun := hrun a₂
  have hE' : Exact p a₂ (φ a₂) :=
    Exact.congr_length_right p a₂ b (φ a₂)
      (Exact.congr_length p a a₂ b hE (teq_length hpub hta))
      (teq_length hpub (hconst a₂).symm)
  obtain ⟨qA, hRa₂⟩ := ha₂.1
  obtain ⟨qB, hRb₂⟩ := hBrun.1
  refine ⟨weave p a₂ (φ a₂), ⟨⟨(qA, qB), ?_⟩, ?_⟩, ?_⟩
  · exact par_reach_interleave (Exact.interleave p a₂ (φ a₂) hE') hRa₂ hRb₂
  · refine consistent_weave hpub p a₂ (φ a₂) w₂ ?_ hBrun.2
    intro t₁ α v t₂ heq
    have hpre : t₁ <+: a₂ := ⟨(Lbl.inp α v :: t₂), heq.symm⟩
    have h := ha₂.2 t₁ α v t₂ heq
    simp only [Insertion.induced_apply, policyIns'_σ] at h
    simp only [Insertion.induced_apply, weaveIns_σ]
    rwa [hcaus a₂ t₁ hpre] at h
  · rw [hp]; exact teq_weave hpub hta (hconst a₂).symm

/-! ### The coalition instance

    Coalition noninterference is INI in the coalition context, so the theorem
    above applies to it verbatim.  Presence being public, the only hypothesis left
    is the existence of a respectful causal policy for one of the two components:
    **that is the whole of what separates the present development from
    compositionality of coalition noninterference over an arbitrary lattice.** -/

theorem coalition_compositional_of_policy (hpub : PublicPresence S.coalition)
    {StA StB : Type} {stepA : StA → Act Channel Value → StA → Prop}
    {stepB : StB → Act Channel Value → StB → Prop} {sA : StA} {sB : StB}
    (C : Coalition Level) (hA : S.coalition.StratNI stepA sA)
    {w₁ w₂ : S.coalition.Strategy Value} (hw : S.coalition.seq C w₁ w₂)
    {t : List (Lbl Channel Value)}
    (ht : S.coalition.produces (parStep stepA stepB) w₁ (sA, sB) t)
    (hpol : ∀ p b, (∃ q, Reach stepB sB b q) → HasPolicy' hpub stepB sB C w₂ p b) :
    ∃ t₂, S.coalition.produces (parStep stepA stepB) w₂ (sA, sB) t₂ ∧
      S.coalition.teq C t t₂ :=
  compositional_of_policy' hpub (fun a => hpub a C) hA hw ht hpol

/-! ### An unconditional instance

    A component that never reads has a policy outright -- its own trace, whatever
    the partner does -- so it composes with any coalition-noninterfering partner
    over any lattice, with no hypothesis beyond public presence. -/

/-- A trace with no inputs. -/
def InputFree (t : List (Lbl Channel Value)) : Prop :=
  ∀ (t₁ : List (Lbl Channel Value)) (a : Channel) (v : Value) t₂,
    t ≠ t₁ ++ Lbl.inp a v :: t₂

theorem hasPolicy'_of_inputFree (hpub : PublicPresence S) {St₂ : Type}
    {step₂ : St₂ → Act Channel Value → St₂ → Prop} {sB : St₂} {ℓ : Level}
    {w : S.Strategy Value} {p : List Bool} {b : List (Lbl Channel Value)}
    (hb : ∃ q, Reach step₂ sB b q) (hfree : InputFree (Value := Value) b) :
    HasPolicy' hpub step₂ sB ℓ w p b :=
  ⟨fun _ => b, fun _ => rfl, fun _ _ _ _ => rfl, fun _ _ _ => rfl,
   fun _ => ⟨hb, fun t₁ a v t₂ heq => absurd heq (hfree t₁ a v t₂)⟩⟩

/-- **Coalition noninterference composes with a component that never reads**, over
    an arbitrary lattice, with no hypothesis beyond public presence. -/
theorem coalition_compositional_inputFree (hpub : PublicPresence S.coalition)
    {StA StB : Type} {stepA : StA → Act Channel Value → StA → Prop}
    {stepB : StB → Act Channel Value → StB → Prop} {sA : StA} {sB : StB}
    (C : Coalition Level) (hA : S.coalition.StratNI stepA sA)
    (hfree : ∀ (t : List (Lbl Channel Value)) (q : StB), Reach stepB sB t q →
      InputFree (Value := Value) t)
    {w₁ w₂ : S.coalition.Strategy Value} (hw : S.coalition.seq C w₁ w₂)
    {t : List (Lbl Channel Value)}
    (ht : S.coalition.produces (parStep stepA stepB) w₁ (sA, sB) t) :
    ∃ t₂, S.coalition.produces (parStep stepA stepB) w₂ (sA, sB) t₂ ∧
      S.coalition.teq C t t₂ :=
  coalition_compositional_of_policy hpub C hA hw ht
    (fun _ b hb => hasPolicy'_of_inputFree hpub hb
      (by obtain ⟨q, hq⟩ := hb; exact hfree b q hq))

end Sec

end InteractiveNI
