/-
  Compositionality over the two-point lattice.

  `two-point-proof.md` proves the conjecture for `L = {L, H}`.  The proof has two
  halves:

  (a) a *game-theoretic* half: `B ∈ Strat-NI` implies `B` has a causal policy
      producing its target ℓ-view against every legal strategy (Lemma (★) there,
      by Zermelo determinacy of a finite perfect-information game, the perfect
      information coming from the H-user seeing the whole trace);

  (b) an *algebraic* half: given such a policy, the composition matches.

  This file formalises (b) in full, with (a) appearing as the hypothesis
  `HasPolicy`.  The essential point of (b) is that a policy which produces its
  target ℓ-view *exactly* makes the partner-generating map ℓ-constant, which is
  what keeps the induced strategy on the other component legal on low channels.
-/
import InteractiveNI.Chain

namespace InteractiveNI

open Classical
attribute [local instance] Classical.propDecidable

namespace Sec

variable {Level Channel Value : Type} {S : Sec Level Channel}

/-- The users of ℓ-invisible channels see everything.  This holds in the
    two-point lattice, where the only ℓ-invisible level is the top one, and it is
    exactly what licenses the determinacy argument of `two-point-proof.md`. -/
def Omniscient (S : Sec Level Channel) (Value : Type) (ℓ : Level) : Prop :=
  ∀ a : Channel, ¬ S.le (S.valL a) ℓ →
    ∀ t₁ t₂ : List (Lbl Channel Value), S.teq (S.valL a) t₁ t₂ → t₁ = t₂

/-- An insertion generated by a partner **policy** `φ`: the partner's trace is a
    function of this component's trace, whose ℓ-view is always the fixed `b`. -/
noncomputable def policyIns (hpub : PublicPresence S) {ℓ : Level}
    (hom : Omniscient S Value ℓ) (hpresℓ : ∀ a : Channel, S.le (S.presL a) ℓ)
    (p : List Bool) (φ : List (Lbl Channel Value) → List (Lbl Channel Value))
    (b : List (Lbl Channel Value)) (hconst : ∀ u, S.teq ℓ (φ u) b) :
    Insertion S Value where
  σ := fun _ u => weave p u (φ u)
  resp_val := by
    intro a t₁ t₂ h
    by_cases hl : S.le (S.valL a) ℓ
    · refine teq_weave hpub h ?_
      exact teq_mono hl ((hconst t₁).trans (hconst t₂).symm)
    · rw [hom a hl t₁ t₂ h]
  resp_pres := by
    intro a t₁ t₂ h
    refine teq_weave hpub h ?_
    exact teq_mono (hpresℓ a) ((hconst t₁).trans (hconst t₂).symm)

@[simp] theorem policyIns_σ (hpub : PublicPresence S) {ℓ : Level}
    (hom : Omniscient S Value ℓ) (hpresℓ : ∀ a : Channel, S.le (S.presL a) ℓ)
    (p : List Bool) (φ : List (Lbl Channel Value) → List (Lbl Channel Value))
    (b : List (Lbl Channel Value)) (hconst : ∀ u, S.teq ℓ (φ u) b)
    (a : Channel) (u : List (Lbl Channel Value)) :
    (policyIns hpub hom hpresℓ p φ b hconst).σ a u = weave p u (φ u) := rfl

/-- **Lemma (★), composed form.**  `B` has a causal policy `φ`: whatever `A`'s
    trace `u`, the partner trace `φ u` is a genuine run of `B` against the
    strategy induced by freezing `A` at `u`, and its ℓ-view is always `b`. -/
def HasPolicy (hpub : PublicPresence S) {St₂ : Type}
    (step₂ : St₂ → Act Channel Value → St₂ → Prop) (sB : St₂) (ℓ : Level)
    (w : S.Strategy Value) (p : List Bool) (b : List (Lbl Channel Value)) : Prop :=
  ∃ φ : List (Lbl Channel Value) → List (Lbl Channel Value),
    (∀ u, S.teq ℓ (φ u) b) ∧
    -- causality: what the policy has emitted by the time `A` has produced a
    -- prefix `t₁` of `u` does not depend on the rest of `u`
    (∀ u t₁, t₁ <+: u → weave p t₁ (φ t₁) = weave p t₁ (φ u)) ∧
    (∀ u, S.produces step₂ ((weaveIns hpub (p.map not) u).induced w) sB (φ u))

/-- **Compositionality from a partner policy.**  This is half (b) of the
    two-point-lattice proof: with `B`'s policy in hand, `A` is re-planned by its
    own noninterference and the two fit together with no fixed point. -/
theorem compositional_of_policy (hpub : PublicPresence S)
    {St₁ St₂ : Type} {step₁ : St₁ → Act Channel Value → St₁ → Prop}
    {step₂ : St₂ → Act Channel Value → St₂ → Prop} {sA : St₁} {sB : St₂}
    {ℓ : Level} (hom : Omniscient S Value ℓ) (hpresℓ : ∀ a : Channel, S.le (S.presL a) ℓ)
    (hA : S.INI step₁ (fun _ => True) sA)
    {w₁ w₂ : S.Strategy Value} (hw : S.seq ℓ w₁ w₂)
    {t : List (Lbl Channel Value)}
    (ht : S.produces (parStep step₁ step₂) w₁ (sA, sB) t)
    (hpol : ∀ p b, HasPolicy hpub step₂ sB ℓ w₂ p b) :
    ∃ t₂, S.produces (parStep step₁ step₂) w₂ (sA, sB) t₂ ∧ S.teq ℓ t t₂ := by
  obtain ⟨q, hreach⟩ := ht.1
  obtain ⟨a, b, hRa, hRb, hI⟩ := par_decompose hreach
  obtain ⟨p, hp, hE⟩ := hI.exists_weave
  have hcons : S.consistent w₁ (weave p a b) := hp ▸ ht.2
  obtain ⟨φ, hconst, hcaus, hrun⟩ := hpol p b
  -- the two induced strategies on `A`
  have hAprod : S.produces step₁ ((weaveIns hpub p b).induced w₁) sA a :=
    ⟨⟨q.1, hRa⟩, consistent_weave_left hpub hE hcons⟩
  have hseq : S.seq ℓ ((weaveIns hpub p b).induced w₁)
      ((policyIns hpub hom hpresℓ p φ b hconst).induced w₂) := by
    intro α u
    refine ⟨fun hl => ?_, fun hl => ?_⟩ <;>
      simp only [Insertion.induced_apply, weaveIns_σ, policyIns_σ]
    · have : w₂.ω α (weave p u b) = w₂.ω α (weave p u (φ u)) :=
        w₂.resp_val α _ _ (teq_mono hl (teq_weave hpub (rfl : S.teq ℓ u u) (hconst u).symm))
      rw [(hw α (weave p u b)).1 hl, this]
    · refine dotEq.trans ((hw α (weave p u b)).2 hl) ?_
      exact w₂.resp_pres α _ _ (teq_mono hl (teq_weave hpub (rfl : S.teq ℓ u u) (hconst u).symm))
  -- re-plan `A`
  obtain ⟨a₂, ha₂, hta⟩ := hA ℓ _ _ trivial trivial hseq a hAprod
  have hBrun := hrun a₂
  have hE' : Exact p a₂ (φ a₂) :=
    Exact.congr_length_right p a₂ b (φ a₂)
      (Exact.congr_length p a a₂ b hE (teq_length hpub hta))
      (teq_length hpub (hconst a₂).symm)
  obtain ⟨qA, hRa₂⟩ := ha₂.1
  obtain ⟨qB, hRb₂⟩ := hBrun.1
  refine ⟨weave p a₂ (φ a₂), ⟨⟨(qA, qB), ?_⟩, ?_⟩, ?_⟩
  · exact par_reach_interleave (Exact.interleave p a₂ (φ a₂) hE') hRa₂ hRb₂
  · refine consistent_weave hpub p a₂ (φ a₂) w₂ ?_ hBrun.2
    intro t₁ α v t₂ heq
    have hpre : t₁ <+: a₂ := ⟨(Lbl.inp α v :: t₂), heq.symm⟩
    have h := ha₂.2 t₁ α v t₂ heq
    simp only [Insertion.induced_apply, policyIns_σ] at h
    simp only [Insertion.induced_apply, weaveIns_σ]
    rwa [hcaus a₂ t₁ hpre] at h
  · rw [hp]; exact teq_weave hpub hta (hconst a₂).symm

end Sec

end InteractiveNI
